name: frei
favicon: null
layout_spectrum: 0.25534
typography_spectrum: 0.5
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c7c8ca'
    - '#13180b'
    - '#5a6061'
    - '#4bbfde'
    - '#368da4'
  brandStrength: 0.18542529782280326
  lightness: 0.319599577691406
  saturation: 0.4375
  rhythmicContrast: 0.5604265804868191
purpose: []
